#
# Copyright (c) 2013 kaytat
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# $File: //depot/stoker_git/stoker/tini/examples/Flash_Util/gen_constants.pl $
# $Date: 2013/07/23 $
# $Revision: #2 $
# $Author: kaytat $
#

open CONSTANTS, $ARGV[0] or die "Can't find $ARGV[0]\n";

my $state = 0;
my $str_idx = 0;
my $i;
my @vars;

print "// AUTO-GENERATED by gen_constants.pl\n";
print "package flash;\n";
print "public class Flash_Constants {\n";
while (<CONSTANTS>) {
    chomp;
    if (/^\#/) {
        next;
    }
    $_ =~ s/ +//g;
    if ($_ eq "") {
        next;
    }
    $_ =~ s/\:\=/\=/;
    @vars = split('=');
    print "public static final int " . $vars[0] . " = 0x" . $vars[1] . ";\n";
}

print "};\n";
